apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopy-deployment
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      imagePullSecrets:
      - name: docker-secrets
      containers:
      - name: hello-py
        image: docker.io/jfdona23/hello-py:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: cm-front
              key: redis-host