apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-hello-py
spec:
  tls:
  - hosts:
    - hello-py.com
    secretName: tls-secret
  rules:
  - host: hello-py.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-py
          servicePort: 80